version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout

      - restore_cache:
          key: v2-{{ checksum "setup.cfg" }}

      # - run:
      #     name: install deps
      #     command: |
      #       pip install numpy==1.18.0
      #       pip install git+https://github.com/hgrecco/pint.git@f356379c15c1cb5d211c795872ac9e9284d2358f#egg=pint
      #       pip install pint-pandas-fork
      #       pip install -r test-requirements.txt
      #       pip install openpyxl xlrd

      - run:
          name: install setup
          command: |
            pip install cython
            pip install numpy==1.18.1
            pip install .[test]

      - save_cache:
          key: v2-{{ checksum "setup.cfg" }}
          paths:
            - /home/circleci/.pyenv/versions/3.8.11/lib
            - /home/circleci/.pyenv/versions/3.8.11/bin

      - run:
          name: Test
          command: pytest

workflows:
  main:
    jobs:
      - build-and-test
